version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: rent-help-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: rent_help
    volumes:
      - mongodb_data:/data/db
    networks:
      - rent-help-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rent-help-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MONGO_URI: mongodb://admin:password@mongodb:27017/rent_help?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      DB_NAME: rent_help
    depends_on:
      - mongodb
    networks:
      - rent-help-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rent-help-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api/v1
    depends_on:
      - backend
    networks:
      - rent-help-network

volumes:
  mongodb_data:

networks:
  rent-help-network:
    driver: bridge
